/**
 * EXHAUSTIVE BOUND — the complete rendered user-data of every Relay-* stack,
 * verbatim, as a golden literal.
 *
 * User-data is a root-privileged boot script and had ZERO test coverage: the
 * compose-plugin checksum verification could become `sha256sum -c - || true`
 * — an unverified root binary downloaded from a mutable GitHub release asset —
 * and every IAM, tag and volume assertion in the suite stayed green. Partial
 * matching cannot fix that: any probe bounds only the substring it names, and
 * the next escape is the line the probe does not mention. So this pins the
 * WHOLE string, which fails on any added, removed, reordered or edited byte —
 * in lib/relay-stack.ts's boot commands AND in the three assets/ files it
 * inlines.
 *
 * It is deliberately brittle. A deliberate boot-sequence or asset change must
 * update this literal consciously — that edit is the review checkpoint.
 * Regenerate by decoding the Fn::Base64 value of the synthesized instance's
 * UserData; only the environment name is parameterized, because the same stack
 * class is instantiated once per environment.
 */
export function expectedUserData(envName: string): string {
  return [
    "#!/bin/bash",
    // The CreationPolicy resource signal. CDK renders `addSignalOnExitCommand`
    // ahead of every other command, so the trap covers the whole boot — a
    // failure signals FAILURE instead of waiting out the timeout, and a green
    // CREATE_COMPLETE now means /opt/relay was actually written.
    "function exitTrap(){",
    "exitCode=$?",
    `/opt/aws/bin/cfn-signal --stack Relay-${envName} --resource RelayInstance8298494B --region us-east-1 -e $exitCode || echo 'Failed to send Cloudformation Signal'`,
    "}",
    "trap exitTrap EXIT",
    "set -euxo pipefail",
    "dnf install -y aws-cfn-bootstrap",
    "dnf install -y docker",
    "systemctl enable --now docker",
    "install -d -m 0755 /usr/libexec/docker/cli-plugins",
    "curl -fsSL https://github.com/docker/compose/releases/download/v2.29.7/docker-compose-linux-aarch64 -o /usr/libexec/docker/cli-plugins/docker-compose",
    "echo \"6e9fbd5daa20dca5d7d89145081ae8155d68ef2928b497d9f85b54fe0f9dbb2c  /usr/libexec/docker/cli-plugins/docker-compose\" | sha256sum -c -",
    "chmod 0755 /usr/libexec/docker/cli-plugins/docker-compose",
    "install -d -m 0755 /opt/relay",
    "cat <<'RELAY_COMPOSE_EOF' > /opt/relay/docker-compose.yml",
    "# On-instance compose unit, written to /opt/relay/docker-compose.yml by user-data.",
    "#",
    "# healthcheck, RUST_LOG, and port 8080 mirror docker/docker-compose.yml; keep both",
    "# in sync on edit. The differences from local dev are deliberate: the relay",
    "# publishes NO host ports (Caddy is the only thing on 80/443, and the relay is",
    "# reachable only on the compose network), the image comes from the registry",
    "# rather than a local build, and stop_grace_period is widened for production.",
    "#",
    "# RELAY_IMAGE and RELAY_AUTH_TOKEN come from /opt/relay/.env, written by deploy.sh",
    "# at deploy time. No top-level `version:` key: current Compose Specification.",
    "",
    "services:",
    "  caddy:",
    "    # Deliberately mutable minor tag (not digest-pinned): Caddy receives security",
    "    # patches on each instance replacement (AMI refresh / re-deploy). Contrast",
    "    # with the relay image, which IS pinned — by ECR tag immutability plus",
    "    # same-digest promotion across environments — because that supply chain is",
    "    # ours to control end to end.",
    "    image: caddy:2",
    "    restart: unless-stopped",
    "    ports:",
    "      - \"80:80\"",
    "      - \"443:443\"",
    "    volumes:",
    "      # Caddy's default config path — no -c flag needed.",
    "      - /opt/relay/Caddyfile:/etc/caddy/Caddyfile:ro",
    "      # caddy_data holds the Let's Encrypt certificates. Persisted across",
    "      # container restarts, but NOT across instance replacement (residual R3,",
    "      # documented-accepted: LE re-issues, mind the 5-duplicate-certs/week limit).",
    "      - caddy_data:/data",
    "      - caddy_config:/config",
    "    depends_on:",
    "      - relay",
    "",
    "  relay:",
    "    image: ${RELAY_IMAGE:?RELAY_IMAGE must be set}",
    "    restart: unless-stopped",
    "    # The relay handles SIGINT only (STOPSIGNAL SIGINT in docker/Dockerfile.relay);",
    "    # 15s gives the graceful exit room to finish inside the grace window.",
    "    stop_grace_period: 15s",
    "    environment:",
    "      - RUST_LOG=info",
    "      # Fail-closed: an unset/empty RELAY_AUTH_TOKEN aborts `compose up` instead",
    "      # of silently starting an open relay (SC2) — collab-relay's main.rs treats",
    "      # an empty token as \"auth disabled\".",
    "      - RELAY_AUTH_TOKEN=${RELAY_AUTH_TOKEN:?RELAY_AUTH_TOKEN must be set; refusing to start an unauthenticated relay}",
    "      # RELAY_SUBSCRIBE_AUTHZ must stay unset/off — see the Environment variable",
    "      # constraint in 01-logic-design.md; it deadlocks the MLS bootstrap handshake.",
    "      # Admission control lives entirely in the Identify exchange.",
    "    healthcheck:",
    "      test: [\"CMD\", \"nc\", \"-z\", \"localhost\", \"8080\"]",
    "      interval: 10s",
    "      timeout: 5s",
    "      retries: 5",
    "      start_period: 5s",
    "",
    "volumes:",
    "  caddy_data:",
    "  caddy_config:",
    "",
    "RELAY_COMPOSE_EOF",
    "cat <<'RELAY_CADDYFILE_EOF' > /opt/relay/Caddyfile",
    `relay-${envName}.collab.example.com {`,
    "\treverse_proxy relay:8080",
    "}",
    "",
    "RELAY_CADDYFILE_EOF",
    "cat <<'RELAY_DEPLOYSH_EOF' > /opt/relay/deploy.sh",
    "#!/usr/bin/env bash",
    "# /opt/relay/deploy.sh — run as root via SSM SendCommand (AWS-RunShellScript).",
    "# $1 is the full image ref, e.g. <acct>.dkr.ecr.<region>.amazonaws.com/obsidian-ee/collab-relay:sha-abc123def456",
    "# Immutable registry tags make a tag ref equivalent to a digest pin.",
    "set -euo pipefail",
    "",
    "IMAGE=\"${1:?usage: deploy.sh <full-image-ref>}\"",
    "REGION=\"us-east-1\"",
    `TOKEN_PARAM="/relay/${envName}/auth-token"`,
    "",
    "# Compose auto-loads .env from the project directory only. SSM RunShellScript's",
    "# working directory is not /opt/relay, and without this cd the ${RELAY_IMAGE} /",
    "# ${RELAY_AUTH_TOKEN} substitutions resolve empty; docker-compose.yml's",
    "# `:?` guards then abort `compose up` rather than starting an open relay (SC2).",
    "cd /opt/relay",
    "",
    "# Registry login. The registry host is the image ref's first path segment, so",
    "# this stays correct without baking the account id into the template.",
    "aws ecr get-login-password --region \"$REGION\" \\",
    "  | docker login --username AWS --password-stdin \"${IMAGE%%/*}\"",
    "",
    "# The token is fetched fresh at deploy time and never lands in an image, a",
    "# workflow log, or a repository variable.",
    "RELAY_AUTH_TOKEN=$(aws ssm get-parameter --region \"$REGION\" \\",
    "  --name \"$TOKEN_PARAM\" --with-decryption --query Parameter.Value --output text)",
    "",
    "[ -n \"${RELAY_AUTH_TOKEN}\" ] || { echo \"FATAL: empty auth token; refusing to start an unauthenticated relay\" >&2; exit 1; }",
    "",
    "umask 077",
    "cat > /opt/relay/.env <<EOF",
    "RELAY_IMAGE=${IMAGE}",
    "RELAY_AUTH_TOKEN=${RELAY_AUTH_TOKEN}",
    "EOF",
    "",
    "# Length only — never echo the value.",
    "echo \"auth token loaded (${#RELAY_AUTH_TOKEN} chars)\"",
    "",
    "docker compose pull relay",
    "docker compose up -d",
    "docker image prune -af",
    "",
    "echo \"deployed ${IMAGE}\"",
    "",
    "RELAY_DEPLOYSH_EOF",
    "chmod 0755 /opt/relay/deploy.sh",
  ].join('\n');
}
